// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Implements message translation functionality.
 *
 * - `translateMessage`: Translates a given message to a specified target language.
 * - `TranslateMessageInput`: The input type for the `translateMessage` function.
 * - `TranslateMessageOutput`: The output type for the `translateMessage` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TranslateMessageInputSchema = z.object({
  text: z.string().describe('The message to translate.'),
  targetLanguage: z.string().describe('The ISO 639-1 code of the target language.'),
});

export type TranslateMessageInput = z.infer<typeof TranslateMessageInputSchema>;

const TranslateMessageOutputSchema = z.object({
  translatedText: z.string().describe('The translated message.'),
});

export type TranslateMessageOutput = z.infer<typeof TranslateMessageOutputSchema>;

export async function translateMessage(input: TranslateMessageInput): Promise<TranslateMessageOutput> {
  return translateMessageFlow(input);
}

const translateMessagePrompt = ai.definePrompt({
  name: 'translateMessagePrompt',
  input: {schema: TranslateMessageInputSchema},
  output: {schema: TranslateMessageOutputSchema},
  prompt: `Translate the following text to {{targetLanguage}}:\n\n{{text}}`,
});

const translateMessageFlow = ai.defineFlow(
  {
    name: 'translateMessageFlow',
    inputSchema: TranslateMessageInputSchema,
    outputSchema: TranslateMessageOutputSchema,
  },
  async input => {
    const {output} = await translateMessagePrompt(input);
    return output!;
  }
);
